imports:
    - { resource: alias.yml }
    - { resource: userdetails_constants.yml }
    - { resource: arraydata.yml }

services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
            $tables: '%tables%'
            $ext_images_path: '%core.root_path%ext/david63/userdetails/adm/style/images'
            $select_ary: '%select_ary%'
            $constants: '%constants%'
        public: true

    david63.userdetails.data.controller:
        class: david63\userdetails\controller\data_controller

    david63.userdetails.core.functions:
        class: david63\userdetails\core\functions
